name: Check for Broken Links

# This action will run whenever you push new code to your main branch
on:
  push:
    branches:
      - main
  # You can also run it on a schedule (e.g., every Monday at 1 AM)
  # schedule:
  #   - cron: '0 1 * * 1'

jobs:
  link-checker:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout the repository code
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Set up and build quarto site
      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2

      - name: Build Quarto Site
        run: quarto render

      # Step 3: Run the broken link checker
      - name: Check for broken links
        id: lychee
        uses: lycheeverse/lychee-action@v2
        with:
          args: --exclude-path ./doxygen .
          fail: true
      