on:
  workflow_dispatch:
  schedule:
    - cron: '0 21 * * 3' # Every Wednesday at 3 PM EST

concurrency:
  group: ${{ github.workflow}}-${{ github.ref }}
  cancel-in-progress: true

name: Weekly checks and updates

jobs:
  weekly-pkgdown-list:
    runs-on: ubuntu-latest
    env:
      R_REMOTES_NO_ERRORS_FROM_WARNINGS: true
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
  
      - uses: r-lib/actions/setup-r@v2
  
      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          packages:
            any::knitr
            any::rmarkdown
            any::gh
            any::purrr
            any::tibble
            any::dplyr
  
      - name: Check if pkgdown sites need updating and update
        run: Rscript .github/get_pkgdown_sites.R
  
      - name: Check for changes to qmd file
        id: git-check
        run: |
          git config --global user.email "gh-actions@github.com"
          git config --global user.name "GitHub Actions"
          git add sites/sites_index.qmd
          git diff --cached --quiet || echo "changed=true" >> $GITHUB_OUTPUT
          
      - name: Get top contributor username
        id: topcontrib
        run: |
          echo "TOP_CONTRIB=$(cat top_contributors.txt)" >> $GITHUB_ENV
          rm top_contributors.txt
          
      - name: Create Pull Request for updated sites_index.qmd
        if: steps.git-check.outputs.changed == 'true'
        uses: peter-evans/create-pull-request@v6
        with:
          commit-message: "Update fims-packages.yaml for new pkgdown site in FIMS org"
          branch: auto/pkgdown-update
          title: "Update fims-packages.yaml for new pkgdown site in FIMS org"
          reviewers: | 
            e-perl-NOAA 
            ${{ env.TOP_CONTRIB }}
          body: |
            :sparkles: **Automated update to `resources/fims-packages.yaml`** :sparkles:
              
            Hey ðŸ‘‹ ${{ env.TOP_CONTRIB }}, your packageâ€™s pkgdown site has been added!
  
            Please add appropriate **categories** to the newly listed pkgdown site in `resources/fims-packages.yaml` to help with site indexing and discovery.
            Also, please add your package's hex logo to the images folder.
  
            - Edit this pull request to add or update categories and package hex logo as needed.
            - Once reviewed,  merge this PR.

  weekly-update-changelog:
    runs-on: ubuntu-latest
    env:
      R_REMOTES_NO_ERRORS_FROM_WARNINGS: true
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
  
      - uses: r-lib/actions/setup-r@v2
  
      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          packages:
            any::httr
            any::jsonlite
            any::glue
  
      - name: Check if pkgdown sites need updating and update
        run: Rscript .github/change_log.R

      - name: Check for changes to FIMS_CHANGELOG.qmd
        id: git-check
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          git add about/FIMS_CHANGELOG.qmd
          git diff --cached --ignore-space-at-eol --quiet || echo "changed=true" >> $GITHUB_OUTPUT
  
      - name: Create Pull Request for updated changelog
        if: steps.git-check.outputs.changed == 'true'
        uses: peter-evans/create-pull-request@v6
        with:
          commit-message: "Update FIMS_CHANGELOG.qmd with latest FIMS releases"
          branch: auto/fims-changelog-update
          title: "Update FIMS_CHANGELOG.qmd"
          body: |
            :robot: This automated PR updates `FIMS_CHANGELOG.qmd` with the latest releases from [NOAA-FIMS/FIMS](https://github.com/NOAA-FIMS/FIMS). 
          labels: |
            changelog
          reviewers: e-perl-NOAA